import Head from "next/head";
import Image from "next/image";
import { Container, Form, Button } from "react-bootstrap";
import Navbar from "../components/Navbar";
import styles from "../styles/index.module.css";

export default function Home() {
  return (
    <>
      <section className={`${styles.mainPage} bg-light vh-100`}>
        <Head>
          <title>Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="./favicon.ico" />
        </Head>
        <Navbar />
        <div className={styles.wave}>
          <svg
            data-name="Layer 1"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1200 120"
            preserveAspectRatio="none"
          >
            <path
              d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z"
              className={styles.shapeFill}
            ></path>
          </svg>
        </div>

        <Container className="d-md-flex justify-content-between">
          <div className="w-50">
            <h1 className="display-1 text-primary mt-5">Blog.io</h1>
            <h2 className="text-secondary mb-5">Record your thoughts</h2>
            <p className="mb-5">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore
              commodi aliquid laboriosam maiores, nostrum molestiae perspiciatis
              placeat fugiat perferendis a accusantium! Facilis deserunt commodi
              quis voluptas nisi quod recusandae quisquam atque delectus
              consequuntur, laborum consequatur autem magni sint voluptatum
              ratione modi ut, quia beatae unde corrupti esse distinctio! Ea,
              ut?
            </p>
            <Button className="me-4">Login</Button>
            <Button variant="danger">Sign up</Button>
          </div>
          <Image
            className="w-50 img-fluid"
            src={"/undraw_dreamer_re_9tua.svg"}
            width={"500px"}
            height={"500px"}
          />
        </Container>
      </section>

      <section className="vh-100 bg-dark bg-gradient"></section>
    </>
  );
}
